name = "ds-invite"
main = "src/worker.js"
assets = { directory = "./public" }
compatibility_date = "2025-11-11"
workers_dev = false

[vars]
GUILD_ID = "879811697559367820"
STUDENT_ROLE_ID = "879812347504521256"

API_URL = "https://ds.transistemas.org"
REDIRECT_URL = "https://ds.transistemas.org/auth/discord/callback"
INVITE_URL = "https://discord.com/invite/yuYpD6QW74"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true