name = "ds-invite"
main = "src/worker.js"
compatibility_date = "2025-11-29"
workers_dev = true

# CR√çTICO: Agregar html_handling y not_found_handling
[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"

routes = [
  { pattern = "ds.transistemas.org/*", zone_name = "transistemas.org" }
]

[vars]
GUILD_ID = "879811697559367820"
STUDENT_ROLE_ID = "879812347504521256"

API_URL = "https://ds.transistemas.org"
REDIRECT_URI = "https://ds.transistemas.org/auth/discord/callback"
INVITE_URL = "https://discord.com/invite/yuYpD6QW74"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true